package lt.psk.mybatis.dao;

import java.util.List;
import lt.psk.mybatis.model.Airport;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AirportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRPORT
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRPORT
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int insert(Airport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRPORT
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    Airport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRPORT
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    List<Airport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AIRPORT
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int updateByPrimaryKey(Airport record);
}