package lt.psk.mybatis.dao;

import java.util.List;
import lt.psk.mybatis.model.Pilot;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PilotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    int insert(Pilot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    Pilot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    List<Pilot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PILOT
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    int updateByPrimaryKey(Pilot record);
}