package lt.psk.mybatis.dao;

import java.util.List;
import lt.psk.mybatis.model.PlanesPilots;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlanesPilotsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES_PILOTS
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int insert(PlanesPilots record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANES_PILOTS
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    List<PlanesPilots> selectAll();
}