package lt.psk.mybatis.dao;

import java.util.List;
import lt.psk.mybatis.model.Plane;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlaneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int insert(Plane record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    Plane selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    List<Plane> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLANE
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    int updateByPrimaryKey(Plane record);
}