package lt.psk.mybatis.model;

import lt.psk.mybatis.model.Plane;

import java.util.List;

public class Airport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AIRPORT.ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AIRPORT.AIRPORT_ADDRESS
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    private String airportAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AIRPORT.NAME
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    private String name;

    private List<Plane> planes;

    public List<Plane> getPlanes() {
        return planes;
    }

    public void setPlanes(List<Plane> planes) {
        this.planes = planes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AIRPORT.ID
     *
     * @return the value of PUBLIC.AIRPORT.ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AIRPORT.ID
     *
     * @param id the value for PUBLIC.AIRPORT.ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AIRPORT.AIRPORT_ADDRESS
     *
     * @return the value of PUBLIC.AIRPORT.AIRPORT_ADDRESS
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public String getAirportAddress() {
        return airportAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AIRPORT.AIRPORT_ADDRESS
     *
     * @param airportAddress the value for PUBLIC.AIRPORT.AIRPORT_ADDRESS
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public void setAirportAddress(String airportAddress) {
        this.airportAddress = airportAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AIRPORT.NAME
     *
     * @return the value of PUBLIC.AIRPORT.NAME
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AIRPORT.NAME
     *
     * @param name the value for PUBLIC.AIRPORT.NAME
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}