package lt.psk.mybatis.model;

public class PilotsPlanes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOTS_PLANES.PILOTS_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private Integer pilotsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PILOTS_PLANES.PLANES_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private Integer planesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOTS_PLANES.PILOTS_ID
     *
     * @return the value of PUBLIC.PILOTS_PLANES.PILOTS_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public Integer getPilotsId() {
        return pilotsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOTS_PLANES.PILOTS_ID
     *
     * @param pilotsId the value for PUBLIC.PILOTS_PLANES.PILOTS_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setPilotsId(Integer pilotsId) {
        this.pilotsId = pilotsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PILOTS_PLANES.PLANES_ID
     *
     * @return the value of PUBLIC.PILOTS_PLANES.PLANES_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public Integer getPlanesId() {
        return planesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PILOTS_PLANES.PLANES_ID
     *
     * @param planesId the value for PUBLIC.PILOTS_PLANES.PLANES_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setPlanesId(Integer planesId) {
        this.planesId = planesId;
    }
}