package lt.psk.mybatis.model;

public class PlanesPilots {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANES_PILOTS.PLANES_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    private Integer planesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANES_PILOTS.PILOTS_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    private Integer pilotsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANES_PILOTS.PLANES_ID
     *
     * @return the value of PUBLIC.PLANES_PILOTS.PLANES_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public Integer getPlanesId() {
        return planesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANES_PILOTS.PLANES_ID
     *
     * @param planesId the value for PUBLIC.PLANES_PILOTS.PLANES_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public void setPlanesId(Integer planesId) {
        this.planesId = planesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANES_PILOTS.PILOTS_ID
     *
     * @return the value of PUBLIC.PLANES_PILOTS.PILOTS_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public Integer getPilotsId() {
        return pilotsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANES_PILOTS.PILOTS_ID
     *
     * @param pilotsId the value for PUBLIC.PLANES_PILOTS.PILOTS_ID
     *
     * @mbg.generated Tue Apr 06 23:37:19 EEST 2021
     */
    public void setPilotsId(Integer pilotsId) {
        this.pilotsId = pilotsId;
    }
}