package lt.psk.mybatis.model;

import java.util.List;

public class Plane {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.MODEL
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private String planeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLANE.AIRPORT_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    private Integer airportId;

    private List<Pilot> pilots;

    public List<Pilot> getPilots() {
        return pilots;
    }

    public void setPlanes(List<Pilot> pilots) {
        this.pilots = pilots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.ID
     *
     * @return the value of PUBLIC.PLANE.ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.ID
     *
     * @param id the value for PUBLIC.PLANE.ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.MODEL
     *
     * @return the value of PUBLIC.PLANE.MODEL
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.MODEL
     *
     * @param model the value for PUBLIC.PLANE.MODEL
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @return the value of PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public String getPlaneNumber() {
        return planeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.PLANE_NUMBER
     *
     * @param planeNumber the value for PUBLIC.PLANE.PLANE_NUMBER
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setPlaneNumber(String planeNumber) {
        this.planeNumber = planeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLANE.AIRPORT_ID
     *
     * @return the value of PUBLIC.PLANE.AIRPORT_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public Integer getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLANE.AIRPORT_ID
     *
     * @param airportId the value for PUBLIC.PLANE.AIRPORT_ID
     *
     * @mbg.generated Mon Apr 05 21:48:31 EEST 2021
     */
    public void setAirportId(Integer airportId) {
        this.airportId = airportId;
    }
}